name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.20
        with:
          index: true
          input: content
          output: assets/indices
          root: .
     
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with: 
          node-version: 20.x
            
      - name: install NPM Deps
        run: npm i
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true
          
      - name: PreBuild
        run: ls -alh node_modules
        
      - name: Create Floating Ui Core Folder
        run: mkdir -p assets/js/floating-ui-core
    
      - name: Copy Floating Ui Core
        run: cp --recursive --force node_modules/@floating-ui/core/dist/* assets/js/floating-ui-core/.
        
      - name: Create Floating Ui DOM Folder
        run: mkdir -p assets/js/floating-ui-dom
            
      - name: Copy Floating Ui DOM
        run: cp --recursive --force node_modules/@floating-ui/dom/dist/* assets/js/floating-ui-dom/.

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master  # deploying branch
          cname: https://puppygirlbelly.github.io
